version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - resolute

  dh.mvcui:
    build:
      context: .
      dockerfile: src/DH.MVCUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - rabbitmq
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "8080:80"
      - 443
    networks:
      - resolute
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa708WoRD"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - resolute

  dh.rabbitmqconsumer:
    build:
      context: .
      dockerfile: src/DH.RabbitMQConsumer/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - resolute

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - resolute
networks:
  resolute:
    driver: bridge
